/* Set this to the Apps Script Web App /exec URL when ready. */
const API_URL = 'https://script.google.com/macros/s/AKfycbxw5VAEi-mJeoKuyCujgF01T8t0mryDp7FqHjrVdl7MXKLjvmiHZoVoIM65VpkCmUgXjw/exec';
const CATS = ['Sub Junior','Junior','Senior','Super Senior','General Senior','General Junior'];
const TEAMS = ['Qiyadah','Rifadah','Siyadah','Wifadah'];
const demo = {students:[],programs:[],candidates:[],results:[],wall:[]};
const state={session:null,data:structuredClone(demo),view:'candidates',cat:'Sub Junior',program:'',chosen:[],loading:false};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const same=(a,b)=>String(a??'').trim().toLowerCase().replace(/[\-_]+/g,' ').replace(/\s+/g,' ')===String(b??'').trim().toLowerCase().replace(/[\-_]+/g,' ').replace(/\s+/g,' ');
function setBusy(button,label){if(!button)return()=>{};const original=button.innerHTML;button.disabled=true;button.textContent=label;return()=>{button.disabled=false;button.innerHTML=original}}
function canonicalTeam(value){const key=String(value??'').trim().toLowerCase();return ['Qiyadah','Rifadah','Siyadah','Wifadah'].find(t=>t.toLowerCase()===key)||String(value??'').trim()}
function isAdmin(){return state.session?.role==='Admin'} function team(){return canonicalTeam(state.session?.team)}
function candidates(){return state.data.candidates.map(c=>{const x=Array.isArray(c)?{id:c[0],team:c[1],category:c[2],program:c[3],chest:c[4],name:c[5],submitted:c[6]}:c;return {...x,team:canonicalTeam(x.team),category:canonicalCategory(x.category)}})}
function students(){return state.data.students.map(s=>{const x=Array.isArray(s)?{chest:s[0],name:s[1],category:s[2],team:s[3]}:s;return {...x,team:canonicalTeam(x.team),category:canonicalCategory(x.category)}})}
function canonicalCategory(value){const key=String(value??'').trim().toLowerCase().replace(/[\-_]+/g,' ').replace(/\s+/g,' ');return CATS.find(c=>c.toLowerCase()===key)||String(value??'').trim()}
function eligibleStudentCategory(studentCategory,programCategory){const student=canonicalCategory(studentCategory),program=canonicalCategory(programCategory);if(program==='General Senior')return student==='Senior'||student==='Super Senior';if(program==='General Junior')return student==='Sub Junior'||student==='Junior';return student===program}
function resultMode(value){const mode=String(value??'I').trim().toUpperCase();return ['G1','G2'].includes(mode)?mode:'I'}
function programs(){return state.data.programs.map(p=>{const x=Array.isArray(p)?{category:p[0],name:p[1],count:+p[2],grading:p[3],resultType:p[4]}:p;return {...x,category:canonicalCategory(x.category),name:String(x.name??'').trim(),grading:String(x.grading??x.Grading??'Grade A').trim(),resultType:resultMode(x.resultType??x['Result Type']??x['Entry Type']??x.Type)}})}
function results(){return state.data.results.map(r=>{const x=Array.isArray(r)?{id:r[0],program:r[1],category:r[2],first:r[3],second:r[4],third:r[5],firstPoints:r[6],secondPoints:r[7],thirdPoints:r[8],status:r[9],updated:r[11],resultType:r[12]}:r;return {...x,resultType:resultMode(x.resultType)}})}
function gradePoints(grading){const g=String(grading??'').trim().toLowerCase();return g==='grade b'?[7,5,3]:g==='grade c'?[10,7]:[3,2,1]}
function toast(msg){document.body.insertAdjacentHTML('beforeend',`<div class="toast">${esc(msg)}</div>`);setTimeout(()=>$('.toast')?.remove(),2600)}
async function api(action,payload={}){if(!API_URL) return localApi(action,payload);const res=await fetch(API_URL,{method:'POST',body:JSON.stringify({action,token:state.session?.token,...payload})});const data=await res.json();if(!data.ok)throw Error(data.error||'Request failed');return data.data}
function localApi(action,p){if(action==='login'){if(p.password!=='demo')throw Error('Demo password is “demo”.');return {role:p.user==='Admin'?'Admin':'Captain',team:p.user==='Admin'?'':p.user,token:'demo'}}if(action==='bootstrap')return state.data;if(action==='saveCandidates'){state.data.candidates=state.data.candidates.filter(c=>c.team!==team()||!same(c.program,p.program)||!same(c.category,p.category));p.students.forEach((s,i)=>state.data.candidates.push({id:`D${Date.now()+i}`,team:team(),category:p.category,program:p.program,chest:s.chest,name:s.name,submitted:new Date().toLocaleString()}));return state.data.candidates}if(action==='saveResult'){let r={...p.result,id:p.result.id||`R${Date.now()}`,updated:new Date().toLocaleString()};let i=state.data.results.findIndex(x=>x.id===r.id||(same(x.program,r.program)&&same(x.category,r.category)));if(i>=0)state.data.results[i]=r;else state.data.results.push(r);return state.data.results}if(action==='publishResult'){state.data.results.find(x=>x.id===p.id).status='Published';return state.data.results}if(action==='wall')return state.data.wall;throw Error('Demo action unavailable')}
async function boot(){if(location.pathname.endsWith('/wall')||location.pathname.endsWith('/wall.html'))return wall();if(location.protocol!=='file:'&&'serviceWorker'in navigator){navigator.serviceWorker.register('./service-worker.js').then(r=>r.update()).catch(()=>{})}const saved=localStorage.getItem('waltakunSession');if(saved){state.session=JSON.parse(saved);try{state.data=await api('bootstrap');render()}catch(e){localStorage.removeItem('waltakunSession');state.session=null;renderLogin();$('#loginError').textContent='Could not load live Google Sheets data: '+e.message}}else renderLogin()}
function logo(){return '<img src="assets/waltakun-logo-red.png" alt="WALTAKUN 26 logo">'}
function renderLogin(){document.title='WALTAKUN 26';$('#app').innerHTML=`<main class="login"><section class="login-art">${logo()}<h1>Sports &<br>Arts Fest</h1><p>One calm control centre for nominations, results, and the celebration wall.</p></section><section class="login-panel"><form class="login-card" id="loginForm"><div class="eyebrow">WALTAKUN 2026</div><h2>Welcome back.</h2><p class="hint">Choose your account, then enter its event password.</p><div class="role-grid">${['Qiyadah','Rifadah','Siyadah','Wifadah','Admin'].map((r,i)=>`<button type="button" class="role ${i===0?'active':''}" data-user="${r}">${r}</button>`).join('')}</div><input id="who" value="Qiyadah" type="hidden"><label>Password</label><input id="password" type="password" autocomplete="current-password" required placeholder="Enter password"><button class="primary wide">Sign in</button><div id="loginError" class="error"></div><p class="hint">Live data is loaded from the WALTAKUN Google Sheet.</p></form></section></main>`;document.querySelectorAll('.role').forEach(b=>b.onclick=()=>{document.querySelectorAll('.role').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#who').value=b.dataset.user});$('#loginForm').onsubmit=login}
async function login(e){e.preventDefault();const done=setBusy(e.submitter,'Signing in, please wait…');try{const x=await api('login',{user:$('#who').value,password:$('#password').value});state.session=x;localStorage.setItem('waltakunSession',JSON.stringify(x));state.data=await api('bootstrap');render()}catch(err){$('#loginError').textContent=err.message;done()}}
function render(){const admin=isAdmin();const nav=admin?[['candidates','Candidate lists'],['registration','Registration summary'],['results','Results'],['scoreboard','Scoreboard'],['schedule','Schedule'],['walladmin','Display wall']]:[['candidates','Candidates'],['results','Published results'],['scoreboard','Scoreboard'],['schedule','Schedule']];$('#app').innerHTML=`<div class="shell"><header class="topbar">${logo()}<span class="brand">WALTAKUN 26</span><span class="user-pill">${esc(admin?'ADMIN':team().toUpperCase())}</span><button class="ghost" id="logout">Log out</button></header><div class="layout"><nav class="nav">${nav.map(([v,n])=>`<button class="${state.view===v?'active':''}" data-view="${v}">${n}</button>`).join('')}</nav><main class="main" id="page"></main></div></div>`;$('#logout').onclick=()=>{localStorage.removeItem('waltakunSession');state.session=null;renderLogin()};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});({candidates:renderCandidates,registration:renderRegistrationSummary,results:renderResults,scoreboard:renderScoreboard,schedule:renderSchedule,walladmin:renderWallAdmin}[state.view]||renderCandidates)()}
function head(eyebrow,title,subtitle,action=''){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`}
function tabs(active=state.cat){return `<div class="category-tabs">${CATS.map(c=>`<button data-cat="${c}" class="${c===active?'active':''}">${c}</button>`).join('')}</div>`}
function attachTabs(fn){document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;state.program='';state.chosen=[];fn()})}
function renderCandidates(){if(isAdmin())return renderAdminCandidates();const catPrograms=programs().filter(p=>same(p.category,state.cat));const saved=candidates().filter(c=>c.team===team());const selected=state.program?programs().find(p=>same(p.name,state.program)&&same(p.category,state.cat)):null;$('#page').innerHTML=head('CAPTAIN DESK',`${team()} candidates`,'Select a programme, choose eligible students, then save your team entry.')+`<section class="stats"><div class="stat"><b>${saved.length}</b><span>Saved entries</span></div><div class="stat"><b>${new Set(saved.map(x=>x.category+'|'+x.program)).size}</b><span>Programmes entered</span></div><div class="stat"><b>${programs().length}</b><span>Programmes available</span></div></section>${tabs()}<section class="program-grid">${catPrograms.length?catPrograms.map(p=>{let n=saved.filter(x=>same(x.program,p.name)&&same(x.category,state.cat)).length;return `<button class="program ${same(state.program,p.name)?'active':''}" data-program="${esc(p.name)}"><b>${esc(p.name)}</b><small>${n}/${p.count} selected</small></button>`}).join(''):'<div class="empty">No programmes in this category.</div>'}</section>${selected?candidateChooser(selected):''}<section class="card" style="margin-top:1.4rem"><div class="list-head"><h3>Saved entries</h3><span class="badge">${saved.length} candidates</span></div>${candidateTable(saved,true)}</section>`;attachTabs(renderCandidates);document.querySelectorAll('[data-program]').forEach(b=>b.onclick=()=>{state.program=b.dataset.program;state.chosen=candidates().filter(c=>c.team===team()&&same(c.program,state.program)&&same(c.category,state.cat)).map(c=>c.chest);renderCandidates()});document.querySelectorAll('.edit-program').forEach(b=>b.onclick=()=>{const [cat,name]=b.dataset.edit.split('|||');state.cat=cat;state.program=name;state.chosen=candidates().filter(c=>c.team===team()&&same(c.program,name)&&same(c.category,cat)).map(c=>c.chest);renderCandidates()});document.querySelectorAll('[data-student]').forEach(x=>x.onchange=()=>{state.chosen=Array.from(document.querySelectorAll('[data-student]:checked')).map(x=>x.value)});$('#studentSearch')?.addEventListener('input',e=>{const q=String(e.target.value).trim().toLowerCase();document.querySelectorAll('#studentList .student').forEach(row=>{row.hidden=!!q&&!row.textContent.toLowerCase().includes(q)})});$('#saveCandidates')?.addEventListener('click',saveCandidates)}
function candidateChooser(p){const eligible=students().filter(s=>s.team===team()&&eligibleStudentCategory(s.category,state.cat));const sourceNote=canonicalCategory(state.cat)==='General Senior'?'Senior + Super Senior':canonicalCategory(state.cat)==='General Junior'?'Sub Junior + Junior':state.cat;return `<section class="card" style="margin-top:1.25rem"><div class="list-head"><div><div class="eyebrow">${esc(state.cat)} · ${esc(sourceNote)}</div><h3 style="margin:.15rem 0">${esc(p.name)}</h3></div><span class="badge">Maximum ${p.count}</span></div><div class="chooser"><div><label>Find a student</label><input id="studentSearch" placeholder="Chest no. or name"></div><div><label>Selection</label><div class="hint"><b id="chosenCount">${state.chosen.length}</b> of ${p.count} selected</div></div></div><div class="student-list" id="studentList">${eligible.map(s=>`<label class="student ${state.chosen.includes(s.chest)?'selected':''}"><input data-student value="${esc(s.chest)}" type="checkbox" ${state.chosen.includes(s.chest)?'checked':''}><span><b>${esc(s.name)}</b><small>${esc(s.chest)} · ${esc(s.category)}</small></span></label>`).join('')||'<div class="empty">No students found in this team and category.</div>'}</div><button id="saveCandidates" class="primary wide">Save ${esc(p.name)} selections</button></section>`}
async function saveCandidates(){const p=programs().find(x=>same(x.name,state.program)&&same(x.category,state.cat));if(state.chosen.length>p.count)return toast(`This programme allows only ${p.count} candidates.`);const done=setBusy($('#saveCandidates'),'Saving candidates, please wait…');try{const list=students().filter(s=>state.chosen.includes(s.chest)&&s.team===team()&&eligibleStudentCategory(s.category,state.cat));state.data.candidates=await api('saveCandidates',{program:p.name,category:state.cat,students:list});toast('Candidate list saved.');renderCandidates()}catch(e){toast(e.message);done()}}
function candidateTable(list,editable=false){
  if(!list.length)return '<div class="empty">No candidates have been saved yet.</div>';
  const rows=list.map(c=>'<tr><td>'+esc(c.program)+'</td><td>'+esc(c.chest)+'</td><td>'+esc(c.name)+'</td><td>'+esc(c.team)+'</td>'+(editable?'<td><button class="ghost edit-program" data-edit="'+esc(c.category+'|||'+c.program)+'">Edit</button></td>':'')+'</tr>').join('');
  return '<div class="table-wrap"><table class="table"><thead><tr><th>Programme</th><th>Chest no.</th><th>Name</th><th>Team</th>'+(editable?'<th></th>':'')+'</tr></thead><tbody>'+rows+'</tbody></table></div>';
}
function renderAdminCandidates(){const list=candidates().filter(c=>same(c.category,state.cat));$('#page').innerHTML=head('ADMINISTRATION','Candidate lists','Review all teams, create attendance lists, or use the random spinner.',`<div class="no-print" style="display:flex;gap:.6rem;flex-wrap:wrap"><button id="spinnerBtn" class="primary">Open spinner</button><button id="printBtn" class="secondary">Print selected programmes</button></div>`)+tabs()+`<section class="card"><div class="toolbar no-print"><div><label>Search</label><input id="candidateSearch" placeholder="Programme, chest no. or name"></div><div><label>Programme filter</label><select id="adminProgram"><option value="">All programmes</option>${programs().filter(p=>same(p.category,state.cat)).map(p=>`<option>${esc(p.name)}</option>`).join('')}</select></div></div><div class="print-only"><h2>WALTAKUN 26 — Candidate List</h2><p>${esc(state.cat)}</p></div><div id="adminCandidateTable">${candidateTable(list)}</div></section>`;attachTabs(renderAdminCandidates);$('#candidateSearch').oninput=filterAdminCandidates;$('#adminProgram').onchange=filterAdminCandidates;$('#printBtn').onclick=printList;$('#spinnerBtn').onclick=openSpinner}
function filterAdminCandidates(){const q=$('#candidateSearch').value.toLowerCase(),p=$('#adminProgram').value;let x=candidates().filter(c=>same(c.category,state.cat)&&(!p||same(c.program,p))&&(`${c.program} ${c.chest} ${c.name}`.toLowerCase().includes(q)));$('#adminCandidateTable').innerHTML=candidateTable(x)}
function printList(){const ordered=[...programs()].sort((a,b)=>String(a.category).localeCompare(String(b.category))||String(a.name).localeCompare(String(b.name)));const options=ordered.map((p,i)=>`<label class="student"><input type="checkbox" value="${i}"> <b>${esc(String(p.category).toUpperCase())}</b> — ${esc(p.name)}</label>`).join('');const modal=document.createElement('div');modal.innerHTML=`<div style="position:fixed;inset:0;background:#0008;display:grid;place-items:center;z-index:10"><div class="card" style="width:min(92vw,560px)"><h3>Choose programmes to print</h3><p class="hint">Choose programmes from any category. Compact lists flow together, normally fitting three or more programmes on each A4 page.</p><div class="student-list" style="max-height:360px">${options}</div><div style="display:flex;gap:.6rem;margin-top:1rem"><button class="primary" id="doPrint">Create print list</button><button class="ghost" id="closePrint">Cancel</button></div></div></div>`;document.body.append(modal);$('#closePrint').onclick=()=>modal.remove();$('#doPrint').onclick=()=>{const wanted=Array.from(modal.querySelectorAll('input:checked')).map(x=>ordered[Number(x.value)]);const old=$('#adminCandidateTable').innerHTML;const lists=wanted.map(p=>{const byTeam=Object.fromEntries(TEAMS.map(t=>[t,candidates().filter(c=>same(c.team,t)&&same(c.category,p.category)&&same(c.program,p.name)).map(c=>c.name)]));const rows=Array.from({length:Math.max(1,...TEAMS.map(t=>byTeam[t].length))},(_,i)=>'<tr>'+TEAMS.map(t=>'<td>'+esc(byTeam[t][i]||'')+'</td>').join('')+'</tr>').join('');return '<section class="print-program compact-program-list"><h2>'+esc(p.name)+'</h2><p>'+esc(String(p.category).toUpperCase())+'</p><table class="table"><thead><tr>'+TEAMS.map(t=>'<th>'+esc(t)+'</th>').join('')+'</tr></thead><tbody>'+rows+'</tbody></table></section>'}).join('');$('#adminCandidateTable').innerHTML=lists||'<div class="empty">Choose at least one programme.</div>';modal.remove();window.print();$('#adminCandidateTable').innerHTML=old}}
function openSpinner(){
  const modal=document.createElement('div');modal.className='spinner-modal';document.body.append(modal);
  let mode='team',program='',removed=new Set(),rotation=0;
  const palette=['#720000','#b18922','#282828','#a13a00','#6b4b7e','#1d6d63','#9a335c','#3d5f94'];
  function source(){if(mode==='team')return TEAMS.map(t=>({id:t,label:t}));const [cat,name]=program.split('|||');return candidates().filter(c=>same(c.program,name)&&same(c.category,cat)).map(c=>({id:c.id||`${c.chest}-${c.team}`,label:`${c.name} · ${c.team}`,detail:c.chest}))}
  function draw(){const all=source(),items=all.filter(x=>!removed.has(x.id)),colors=items.map((_,i)=>palette[i%palette.length]),slice=items.length?360/items.length:360;const gradient=items.length?`conic-gradient(${items.map((_,i)=>`${colors[i]} ${i*slice}deg ${(i+1)*slice}deg`).join(',')})`:'#e7dcb7';const wheelLabels=items.map((x,i)=>{const raw=x.detail?`${x.label.split(' · ')[0]} · ${x.detail}`:x.label;const short=raw.length>19?raw.slice(0,18)+'…':raw;return `<b class="wheel-label" style="transform:rotate(${(i+.5)*slice}deg) translateY(-118px) rotate(-${(i+.5)*slice}deg)">${esc(short)}</b>`}).join('');const programOptions=programs().map(p=>{const key=p.category+'|||'+p.name;return `<option value="${esc(key)}" ${key===program?'selected':''}>${esc(p.category.toUpperCase())} — ${esc(p.name)}</option>`}).join('');modal.innerHTML=`<div class="spinner-card"><button class="spinner-close" id="spinnerClose" aria-label="Close">×</button><div class="eyebrow">ADMIN TOOL</div><h2>Random spinner</h2><div class="spinner-modes"><button class="${mode==='team'?'active':''}" id="teamMode">Team Spin</button><button class="${mode==='candidate'?'active':''}" id="candidateMode">Candidate Spin</button></div>${mode==='candidate'?`<label>Programme<select id="spinProgram"><option value="">Choose programme</option>${programOptions}</select></label>`:''}<div class="spinner-stage"><div class="spinner-pointer">▼</div><div class="spin-wheel" id="spinWheel" style="background:${gradient};transform:rotate(${rotation}deg)">${wheelLabels}<span>${items.length}</span></div></div><button id="spinBtn" class="primary wide" ${items.length<1?'disabled':''}>${items.length?'Spin the wheel':'No entries available'}</button><div id="spinWinner" class="spin-winner">${items.length?`${items.length} entries ready`:'Choose a programme or restore entries.'}</div><div class="spin-list"><div class="list-head"><b>Entries in this spin</b><span class="badge">${items.length}</span></div>${items.map(x=>`<div class="spin-entry"><span><b>${esc(x.label)}</b>${x.detail?`<small>${esc(x.detail)}</small>`:''}</span><button class="ghost remove-spin" data-id="${esc(x.id)}">Remove</button></div>`).join('')||'<div class="empty">No available entries.</div>'}</div>${removed.size?'<button id="restoreSpin" class="ghost wide">Restore all removed entries</button>':''}</div>`;
    $('#spinnerClose').onclick=()=>modal.remove();$('#teamMode').onclick=()=>{mode='team';program='';removed.clear();draw()};$('#candidateMode').onclick=()=>{mode='candidate';program='';removed.clear();draw()};$('#spinProgram')?.addEventListener('change',e=>{program=e.target.value;removed.clear();draw()});document.querySelectorAll('.remove-spin').forEach(b=>b.onclick=()=>{removed.add(b.dataset.id);draw()});$('#restoreSpin')?.addEventListener('click',()=>{removed.clear();draw()});$('#spinBtn')?.addEventListener('click',()=>{const current=source().filter(x=>!removed.has(x.id));if(!current.length)return;const index=Math.floor(Math.random()*current.length),turns=6+Math.floor(Math.random()*3);rotation+=turns*360+(360-((index+.5)*(360/current.length)));const button=$('#spinBtn');const done=setBusy(button,'Spinning, please wait…');const wheel=$('#spinWheel');wheel.style.transition='transform 4s cubic-bezier(.18,.72,.18,1)';wheel.style.transform=`rotate(${rotation}deg)`;setTimeout(()=>{const picked=current[index];removed.add(picked.id);$('#spinWinner').innerHTML=`<b>Selected: ${esc(picked.label)}</b><br><small>Removed from this wheel for the next spin.</small>`;done();setTimeout(draw,1700)},4200)})
  }draw();
}
function renderResults(){
  if(!isAdmin())return renderPublishedResults();
  const cat=state.resultCat||state.cat||CATS[0];state.resultCat=cat;
  const ps=programs().filter(p=>same(p.category,cat)),current=ps.some(p=>same(p.name,state.program))?state.program:ps[0]?.name;state.program=current;state.cat=cat;
  const selectedProgram=ps.find(p=>same(p.name,current))||{},points=gradePoints(selectedProgram.grading),entries=candidates().filter(c=>same(c.program,current)&&same(c.category,cat)),existing=results().find(r=>same(r.program,current)&&same(r.category,cat))||{},mode=resultMode(selectedProgram.resultType),groupSize=mode==='G2'?Math.max(1,Math.floor(Number(selectedProgram.count||0)/2)):1;
  const programmeOptions=ps.map(p=>'<option '+(p.name===current?'selected':'')+'>'+esc(p.name)+'</option>').join('');
  const places=[['first','1st place',points[0]],['second','2nd place',points[1]],...(points[2]?[['third','3rd place',points[2]]]:[])].map(x=>{
    if(mode==='G1'){const teams=[...new Set(entries.map(c=>c.team))];const opts=teams.map(t=>'<option value="TEAM|'+esc(t)+'" '+(existing[x[0]]==='TEAM|'+t?'selected':'')+'>'+esc(t)+'</option>').join('');return '<div class="place"><span>'+x[1][0]+'</span><div><b>'+x[1]+'</b><select id="'+x[0]+'"><option value="">Choose team</option>'+opts+'</select><small>Team result</small></div><small>'+x[2]+' points</small></div>'}
    if(mode==='G2'){const selected=String(existing[x[0]]||'').split('|');const members=entries.map(c=>'<label class="student"><input type="checkbox" data-result-group="'+x[0]+'" value="'+esc(c.chest)+'" '+(selected.includes(String(c.chest))?'checked':'')+'><span><b>'+esc(c.name)+'</b><small>'+esc(c.team)+'</small></span></label>').join('');return '<div class="place"><span>'+x[1][0]+'</span><div><b>'+x[1]+'</b><small>Select '+groupSize+' members from one team</small><div class="student-list" style="max-height:180px">'+members+'</div></div><small>'+x[2]+' points</small></div>'}
    const opts=entries.map(c=>'<option value="'+esc(c.chest)+'" '+(existing[x[0]]===c.chest?'selected':'')+'>'+esc(c.name)+' ('+esc(c.chest)+' · '+esc(c.team)+')</option>').join('');return '<label class="place"><span>'+x[1][0]+'</span><select id="'+x[0]+'"><option value="">No selection</option>'+opts+'</select><small>'+x[2]+' points</small></label>';
  }).join('');
  const saved=results(),savedRows=saved.map(r=>'<tr><td>'+esc(r.program)+'</td><td><span class="badge '+r.status.toLowerCase()+'">'+esc(r.status)+'</span></td><td>'+(r.status==='Draft'?'<button class="secondary publish" data-id="'+esc(r.id)+'">Publish</button>':'Published')+'</td></tr>').join('');
  const savedHtml=saved.length?'<div class="table-wrap"><table class="table"><thead><tr><th>Programme</th><th>Status</th><th></th></tr></thead><tbody>'+savedRows+'</tbody></table></div>':'<div class="empty">No results saved.</div>';
  const categoryOptions=CATS.map(c=>'<option '+(same(c,cat)?'selected':'')+'>'+esc(c.toUpperCase())+'</option>').join('');
  const modeNote=mode==='G1'?'Group result: choose the winning team only.':mode==='G2'?'Group result: select '+groupSize+' members from one team for every place.':'Individual result: choose one candidate for every place.';
  $('#page').innerHTML=head('ADMINISTRATION','Results','Choose a category first, then select its programme and add placements.')+'<div class="result-grid"><section class="card"><label>Category</label><select id="resultCategory">'+categoryOptions+'</select><label>Programme</label><select id="resultProgram">'+programmeOptions+'</select><p class="hint"><b>'+esc(selectedProgram.grading||'Grade A')+'</b> · '+points.join(', ')+' points for first'+(points[2]?', second, third':', second')+'.<br>'+esc(modeNote)+'</p><div class="podium" style="margin-top:1.2rem">'+places+'</div><button id="saveResult" class="primary wide">Save draft</button></section><section class="card"><div class="list-head"><h3>Saved results</h3><span class="badge">'+saved.length+'</span></div>'+savedHtml+'</section></div>';
  $('#resultCategory').onchange=e=>{state.resultCat=e.target.value;state.program='';renderResults()};$('#resultProgram').onchange=e=>{state.program=e.target.value;renderResults()};$('#saveResult').onclick=saveResult;document.querySelectorAll('.publish').forEach(b=>b.onclick=()=>publish(b.dataset.id,b));
}
async function saveResult(){const p=programs().find(x=>same(x.name,state.program)&&same(x.category,state.resultCat)),points=gradePoints(p.grading),mode=resultMode(p.resultType),places=['first','second','third'];let picked;if(mode==='G2'){const size=Math.max(1,Math.floor(Number(p.count||0)/2));picked=places.map(place=>Array.from(document.querySelectorAll('[data-result-group="'+place+'"]:checked')).map(x=>x.value));if(!picked[0].length||!picked[1].length)return toast('First and second place are required.');if(picked.filter((_,i)=>i<2||points[2]).some(group=>group.length!==size))return toast('Choose exactly '+size+' members for each place.');const all=picked.flat();if(new Set(all).size!==all.length)return toast('A candidate cannot have two places.');const entries=candidates().filter(c=>same(c.program,p.name)&&same(c.category,p.category));if(picked.some(group=>group.length&&new Set(group.map(ch=>entries.find(c=>String(c.chest)===String(ch))?.team)).size!==1))return toast('Each place must contain members from one team.');picked=picked.map(group=>group.join('|'))}else{picked=places.map(k=>$('#'+k)?.value||'');if(!picked[0]||!picked[1])return toast('First and second place are required.');if(new Set(picked.filter(Boolean)).size!==picked.filter(Boolean).length)return toast(mode==='G1'?'A team cannot have two places.':'A candidate cannot have two places.')}const done=setBusy($('#saveResult'),'Saving result, please wait…'),old=results().find(r=>same(r.program,p.name)&&same(r.category,p.category));try{state.data.results=await api('saveResult',{result:{id:old?.id||'',program:p.name,category:p.category,first:picked[0],second:picked[1],third:points[2]?picked[2]:'',firstPoints:points[0],secondPoints:points[1],thirdPoints:points[2]||'',status:old?.status||'Draft'}});toast('Result saved as draft.');renderResults()}catch(e){toast(e.message);done()}}
async function publish(id,button){const done=setBusy(button,'Publishing, please wait…');try{state.data.results=await api('publishResult',{id});toast('Result published.');renderResults()}catch(e){toast(e.message);done()}}
function renderPublishedResults(){const pub=results().filter(r=>r.status==='Published');const rows=pub.map(r=>'<tr><td><b>'+esc(r.program)+'</b></td><td>'+winner(r.first)+'</td><td>'+winner(r.second)+'</td><td>'+(r.third?winner(r.third):'—')+'</td></tr>').join('');const body=pub.length?'<div class="table-wrap"><table class="table"><thead><tr><th>Programme</th><th>First</th><th>Second</th><th>Third</th></tr></thead><tbody>'+rows+'</tbody></table></div>':'<div class="empty">Results will appear here once the administrator publishes them.</div>';$('#page').innerHTML=head('LIVE RESULTS','Published results','Only confirmed results are shown here.')+'<section class="card">'+body+'</section>'}
function renderRegistrationSummary(){const ps=programs();const rows=TEAMS.map(t=>{const registered=ps.filter(p=>candidates().some(c=>same(c.team,t)&&same(c.category,p.category)&&same(c.program,p.name)));const missing=ps.filter(p=>!registered.includes(p));const missingList=missing.length?missing.map(p=>'<span class="missing-program"><b>'+esc(String(p.category).toUpperCase())+'</b> · '+esc(p.name)+'</span>').join(''):'<span class="complete">All programmes registered</span>';return '<tr><td><b>'+esc(t)+'</b></td><td><b>'+registered.length+' / '+ps.length+'</b></td><td>'+missing.length+'</td><td class="registration-missing">'+missingList+'</td></tr>'}).join('');const totalSaved=TEAMS.reduce((n,t)=>n+ps.filter(p=>candidates().some(c=>same(c.team,t)&&same(c.category,p.category)&&same(c.program,p.name))).length,0);$('#page').innerHTML=head('ADMINISTRATION','Registration summary','See each team’s programme registrations and immediately identify entries still missing.')+'<div class="stats"><article class="stat"><b>'+ps.length+'</b><span>Programmes available per team</span></article><article class="stat"><b>'+totalSaved+'</b><span>Programme registrations saved</span></article></div><section class="card"><p class="hint">A programme is counted as registered when that team has saved at least one participant.</p><div class="table-wrap"><table class="table registration-table"><thead><tr><th>Team</th><th>Registered</th><th>Not registered</th><th>Missing programmes</th></tr></thead><tbody>'+rows+'</tbody></table></div></section>'}
function resultTeam(value){const raw=String(value||'');if(raw.startsWith('TEAM|'))return canonicalTeam(raw.slice(5));const chest=raw.split('|')[0];return candidates().find(c=>String(c.chest)===String(chest))?.team||''}
function renderScoreboard(){const scores=Object.fromEntries(TEAMS.map(t=>[t,{team:t,total:0,...Object.fromEntries(CATS.map(c=>[c,0]))}]));results().filter(r=>r.status==='Published').forEach(r=>{[['first','firstPoints'],['second','secondPoints'],['third','thirdPoints']].forEach(([place,points])=>{const winningTeam=resultTeam(r[place]);if(winningTeam&&scores[winningTeam]){const n=Number(r[points]||0);scores[winningTeam].total+=n;scores[winningTeam][canonicalCategory(r.category)]=(scores[winningTeam][canonicalCategory(r.category)]||0)+n}})});const ordered=Object.values(scores).sort((a,b)=>b.total-a.total||a.team.localeCompare(b.team));const rows=ordered.map((r,i)=>'<tr><td><b>'+ (i+1)+'. '+esc(r.team)+'</b></td>'+CATS.map(c=>'<td>'+r[c]+'</td>').join('')+'<td><b>'+r.total+'</b></td></tr>').join('');$('#page').innerHTML=head('LIVE SCOREBOARD','Team scores','Scores are calculated from published results only.')+'<section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Team</th>'+CATS.map(c=>'<th>'+esc(c.toUpperCase())+'</th>').join('')+'<th>Total</th></tr></thead><tbody>'+rows+'</tbody></table></div></section>'}
function renderSchedule(){$('#page').innerHTML=head('EVENT SCHEDULE','Schedule','View the official WALTAKUN sports schedule.')+'<section class="card"><p class="hint">The schedule is maintained as a PDF. Open it in a new tab or download it for offline use.</p><a class="primary" href="schedule.pdf" target="_blank" rel="noopener">Open schedule PDF ↗</a></section>'}
function winner(value){const raw=String(value||'');if(raw.startsWith('TEAM|'))return '<b>'+esc(raw.slice(5))+'</b>';const members=raw.split('|').filter(Boolean).map(ch=>candidates().find(c=>String(c.chest)===String(ch))).filter(Boolean);if(members.length>1)return members.map(c=>esc(c.name)).join('<br>')+' <small>('+esc(members[0].team)+')</small>';const c=members[0];return c?`${esc(c.name)} <small>(${esc(c.team)})</small>`:esc(raw)}
function renderWallAdmin(){$('#page').innerHTML=head('DISPLAY WALL','TV slideshow','Open the display link on the TV. It rotates published results, poster slides, and an optional result-template slide.',`<button id="openWall" class="secondary">Open display wall ↗</button>`)+`<section class="stats"><div class="stat"><b>${results().filter(r=>r.status==='Published').length}</b><span>Published result slides</span></div><div class="stat"><b>${state.data.wall.filter(x=>x.enabled).length}</b><span>Custom wall slides</span></div><div class="stat"><b>5s</b><span>Slide timing</span></div></section><section class="card"><h3>Custom wall slides</h3><p class="hint">Upload images as <b>wall/W001.jpg</b>, <b>wall/W002.jpg</b>, etc. The Wall sheet uses each row ID to find its local image automatically; the Image URL column can be left blank.</p><table class="table"><thead><tr><th>ID</th><th>Type</th><th>Title</th><th>Enabled</th></tr></thead><tbody>${state.data.wall.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.type||'POSTER')}</td><td>${esc(x.title)}</td><td>${x.enabled?'Yes':'No'}</td></tr>`).join('')||'<tr><td colspan="4">No custom slides yet.</td></tr>'}</tbody></table></section>`;$('#openWall').onclick=()=>window.open('wall.html','_blank')}
function wallImage(slide){const raw=String(slide.imageUrl||slide.image||'').trim();if(/^https?:\/\//i.test(raw))return raw;if(raw)return 'wall/'+(raw.includes('.')?raw:raw+'.jpg');return 'wall/'+String(slide.id).trim()+'.jpg'}
function wallImageTag(slide,className,alt){const primary=wallImage(slide),fallback=primary.startsWith('wall/')?'Wall/'+primary.slice(5):primary;return '<img class="'+className+'" src="'+esc(primary)+'" onerror="if(!this.dataset.wallRetry){this.dataset.wallRetry=\'1\';this.src=\''+esc(fallback)+'\'}" alt="'+esc(alt)+'">'}
async function wall(){document.title='WALTAKUN 26 — Display Wall';try{state.data=await api('wallBootstrap')}catch(e){console.error(e)}const template=state.data.wall.find(x=>x.enabled&&same(x.type,'RESULT TEMPLATE'));const slides=[...results().filter(r=>r.status==='Published').map(r=>({type:'result',r,template})),...state.data.wall.filter(x=>x.enabled&&!same(x.type,'RESULT TEMPLATE')).sort((a,b)=>(a.order||0)-(b.order||0)).map(x=>({type:'image',x}))];if(!slides.length)slides.push({type:'empty'});let i=0;function podium(r){return '<div class="wall-podium">'+[['First',r.first],['Second',r.second],['Third',r.third]].filter(x=>x[1]).map(([p,c])=>'<div class="wall-place"><b>'+p+' PLACE</b><div>'+winner(c)+'</div></div>').join('')+'</div>'}function draw(){const s=slides[i++%slides.length];let body=s.type==='result'?(s.template?'<div class="result-template">'+wallImageTag(s.template,'','Result template')+'<div class="template-copy"><div class="eyebrow">RESULT ANNOUNCEMENT</div><h1>'+esc(s.r.program)+'</h1>'+podium(s.r)+'</div></div>':'<div class="eyebrow" style="color:var(--gold)">RESULT ANNOUNCEMENT</div><h1>'+esc(s.r.program)+'</h1>'+podium(s.r)):s.type==='image'?wallImageTag(s.x,'wall-photo',s.x.title)+'<h1>'+esc(s.x.title)+'</h1><p class="caption">'+esc(s.x.caption)+'</p>':'<h1>WALTAKUN 26</h1><p class="caption">Wall connection not available.</p>';$('#app').innerHTML='<main class="wall"><div class="wall-content">'+(s.type==='result'&&s.template?'':logo())+body+'</div></main>'}draw();setInterval(draw,5000)}
boot();
