/* Set this to the Apps Script Web App /exec URL when ready. */
const API_URL = 'https://script.google.com/macros/s/AKfycbxw5VAEi-mJeoKuyCujgF01T8t0mryDp7FqHjrVdl7MXKLjvmiHZoVoIM65VpkCmUgXjw/exec';
const CATS = ['Sub Junior','Junior','Senior','Super Senior','General Senior','General Junior'];
const demo = {students:[],programs:[],candidates:[],results:[],wall:[]};
const state={session:null,data:structuredClone(demo),view:'candidates',cat:'Sub Junior',program:'',chosen:[],loading:false};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const same=(a,b)=>String(a??'').trim().toLowerCase().replace(/[\-_]+/g,' ').replace(/\s+/g,' ')===String(b??'').trim().toLowerCase().replace(/[\-_]+/g,' ').replace(/\s+/g,' ');
function canonicalTeam(value){const key=String(value??'').trim().toLowerCase();return ['Qiyadah','Rifadah','Siyadah','Wifadah'].find(t=>t.toLowerCase()===key)||String(value??'').trim()}
function isAdmin(){return state.session?.role==='Admin'} function team(){return canonicalTeam(state.session?.team)}
function candidates(){return state.data.candidates.map(c=>{const x=Array.isArray(c)?{id:c[0],team:c[1],category:c[2],program:c[3],chest:c[4],name:c[5],submitted:c[6]}:c;return {...x,team:canonicalTeam(x.team),category:canonicalCategory(x.category)}})}
function students(){return state.data.students.map(s=>{const x=Array.isArray(s)?{chest:s[0],name:s[1],category:s[2],team:s[3]}:s;return {...x,team:canonicalTeam(x.team),category:canonicalCategory(x.category)}})}
function canonicalCategory(value){const key=String(value??'').trim().toLowerCase().replace(/[\-_]+/g,' ').replace(/\s+/g,' ');return CATS.find(c=>c.toLowerCase()===key)||String(value??'').trim()}
function programs(){return state.data.programs.map(p=>{const x=Array.isArray(p)?{category:p[0],name:p[1],count:+p[2]}:p;return {...x,category:canonicalCategory(x.category),name:String(x.name??'').trim()}})}
function results(){return state.data.results.map(r=>Array.isArray(r)?{id:r[0],program:r[1],category:r[2],first:r[3],second:r[4],third:r[5],status:r[6],updated:r[8]}:r)}
function toast(msg){document.body.insertAdjacentHTML('beforeend',`<div class="toast">${esc(msg)}</div>`);setTimeout(()=>$('.toast')?.remove(),2600)}
async function api(action,payload={}){if(!API_URL) return localApi(action,payload);const res=await fetch(API_URL,{method:'POST',body:JSON.stringify({action,token:state.session?.token,...payload})});const data=await res.json();if(!data.ok)throw Error(data.error||'Request failed');return data.data}
function localApi(action,p){if(action==='login'){if(p.password!=='demo')throw Error('Demo password is “demo”.');return {role:p.user==='Admin'?'Admin':'Captain',team:p.user==='Admin'?'':p.user,token:'demo'}}if(action==='bootstrap')return state.data;if(action==='saveCandidates'){state.data.candidates=state.data.candidates.filter(c=>c.team!==team()||c.program!==p.program);p.students.forEach((s,i)=>state.data.candidates.push({id:`D${Date.now()+i}`,team:team(),category:p.category,program:p.program,chest:s.chest,name:s.name,submitted:new Date().toLocaleString()}));return state.data.candidates}if(action==='saveResult'){let r={...p.result,id:p.result.id||`R${Date.now()}`,updated:new Date().toLocaleString()};let i=state.data.results.findIndex(x=>x.id===r.id||x.program===r.program);if(i>=0)state.data.results[i]=r;else state.data.results.push(r);return state.data.results}if(action==='publishResult'){state.data.results.find(x=>x.id===p.id).status='Published';return state.data.results}if(action==='wall')return state.data.wall;throw Error('Demo action unavailable')}
async function boot(){if(location.pathname.endsWith('/wall'))return wall();if(location.protocol!=='file:'&&'serviceWorker'in navigator){navigator.serviceWorker.register('./service-worker.js').then(r=>r.update()).catch(()=>{})}const saved=sessionStorage.getItem('waltakunSession');if(saved){state.session=JSON.parse(saved);try{state.data=await api('bootstrap');render()}catch(e){sessionStorage.removeItem('waltakunSession');state.session=null;renderLogin();$('#loginError').textContent='Could not load live Google Sheets data: '+e.message}}else renderLogin()}
function logo(){return '<img src="assets/logo.png" alt="WALTAKUN 26 logo">'}
function renderLogin(){document.title='WALTAKUN 26';$('#app').innerHTML=`<main class="login"><section class="login-art">${logo()}<h1>Sports &<br>Arts Fest</h1><p>One calm control centre for nominations, results, and the celebration wall.</p></section><section class="login-panel"><form class="login-card" id="loginForm"><div class="eyebrow">WALTAKUN 2026</div><h2>Welcome back.</h2><p class="hint">Choose your account, then enter its event password.</p><div class="role-grid">${['Qiyadah','Rifadah','Siyadah','Wifadah','Admin'].map((r,i)=>`<button type="button" class="role ${i===0?'active':''}" data-user="${r}">${r}</button>`).join('')}</div><input id="who" value="Qiyadah" type="hidden"><label>Password</label><input id="password" type="password" autocomplete="current-password" required placeholder="Enter password"><button class="primary wide">Sign in</button><div id="loginError" class="error"></div><p class="hint">Live data is loaded from the WALTAKUN Google Sheet.</p></form></section></main>`;document.querySelectorAll('.role').forEach(b=>b.onclick=()=>{document.querySelectorAll('.role').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#who').value=b.dataset.user});$('#loginForm').onsubmit=login}
async function login(e){e.preventDefault();try{const x=await api('login',{user:$('#who').value,password:$('#password').value});state.session=x;sessionStorage.setItem('waltakunSession',JSON.stringify(x));state.data=await api('bootstrap');render()}catch(err){$('#loginError').textContent=err.message}}
function render(){const admin=isAdmin();const nav=admin?[['candidates','Candidate lists'],['results','Results'],['walladmin','Display wall']]:[['candidates','Candidates'],['results','Published results']];$('#app').innerHTML=`<div class="shell"><header class="topbar">${logo()}<span class="brand">WALTAKUN 26</span><span class="user-pill">${esc(admin?'ADMIN':team().toUpperCase())}</span><button class="ghost" id="logout">Log out</button></header><div class="layout"><nav class="nav">${nav.map(([v,n])=>`<button class="${state.view===v?'active':''}" data-view="${v}">${n}</button>`).join('')}</nav><main class="main" id="page"></main></div></div>`;$('#logout').onclick=()=>{sessionStorage.removeItem('waltakunSession');state.session=null;renderLogin()};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});({candidates:renderCandidates,results:renderResults,walladmin:renderWallAdmin}[state.view]||renderCandidates)()}
function head(eyebrow,title,subtitle,action=''){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`}
function tabs(active=state.cat){return `<div class="category-tabs">${CATS.map(c=>`<button data-cat="${c}" class="${c===active?'active':''}">${c}</button>`).join('')}</div>`}
function attachTabs(fn){document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;state.program='';state.chosen=[];fn()})}
function renderCandidates(){if(isAdmin())return renderAdminCandidates();const catPrograms=programs().filter(p=>p.category===state.cat);const saved=candidates().filter(c=>c.team===team());const selected=state.program?programs().find(p=>p.name===state.program):null;$('#page').innerHTML=head('CAPTAIN DESK',`${team()} candidates`,'Select a programme, choose eligible students, then save your team entry.')+`<section class="stats"><div class="stat"><b>${saved.length}</b><span>Saved entries</span></div><div class="stat"><b>${new Set(saved.map(x=>x.program)).size}</b><span>Programmes entered</span></div><div class="stat"><b>${programs().length}</b><span>Programmes available</span></div></section>${tabs()}<section class="program-grid">${catPrograms.length?catPrograms.map(p=>{let n=saved.filter(x=>x.program===p.name).length;return `<button class="program ${state.program===p.name?'active':''}" data-program="${esc(p.name)}"><b>${esc(p.name)}</b><small>${n}/${p.count} selected</small></button>`}).join(''):'<div class="empty">No programmes in this category.</div>'}</section>${selected?candidateChooser(selected):''}<section class="card" style="margin-top:1.4rem"><div class="list-head"><h3>Saved entries</h3><span class="badge">${saved.length} candidates</span></div>${candidateTable(saved,true)}</section>`;attachTabs(renderCandidates);document.querySelectorAll('[data-program]').forEach(b=>b.onclick=()=>{state.program=b.dataset.program;state.chosen=candidates().filter(c=>c.team===team()&&c.program===state.program).map(c=>c.chest);renderCandidates()});document.querySelectorAll('.edit-program').forEach(b=>b.onclick=()=>{const p=programs().find(x=>x.name===b.dataset.edit);state.cat=p.category;state.program=p.name;state.chosen=candidates().filter(c=>c.team===team()&&c.program===p.name).map(c=>c.chest);renderCandidates()});document.querySelectorAll('[data-student]').forEach(x=>x.onchange=()=>{state.chosen=Array.from(document.querySelectorAll('[data-student]:checked')).map(x=>x.value)});$('#saveCandidates')?.addEventListener('click',saveCandidates)}
function candidateChooser(p){const eligible=students().filter(s=>s.team===team()&&s.category===state.cat);return `<section class="card" style="margin-top:1.25rem"><div class="list-head"><div><div class="eyebrow">${esc(state.cat)}</div><h3 style="margin:.15rem 0">${esc(p.name)}</h3></div><span class="badge">Maximum ${p.count}</span></div><div class="chooser"><div><label>Find a student</label><input id="studentSearch" placeholder="Chest no. or name"></div><div><label>Selection</label><div class="hint"><b id="chosenCount">${state.chosen.length}</b> of ${p.count} selected</div></div></div><div class="student-list" id="studentList">${eligible.map(s=>`<label class="student ${state.chosen.includes(s.chest)?'selected':''}"><input data-student value="${esc(s.chest)}" type="checkbox" ${state.chosen.includes(s.chest)?'checked':''}><span><b>${esc(s.name)}</b><small>${esc(s.chest)} · ${esc(s.category)}</small></span></label>`).join('')||'<div class="empty">No students found in this team and category.</div>'}</div><button id="saveCandidates" class="primary wide">Save ${esc(p.name)} selections</button></section>`}
async function saveCandidates(){const p=programs().find(x=>x.name===state.program);if(state.chosen.length>p.count)return toast(`This programme allows only ${p.count} candidates.`);try{const list=students().filter(s=>state.chosen.includes(s.chest));state.data.candidates=await api('saveCandidates',{program:p.name,category:state.cat,students:list});toast('Candidate list saved.');renderCandidates()}catch(e){toast(e.message)}}
function candidateTable(list,editable=false){
  if(!list.length)return '<div class="empty">No candidates have been saved yet.</div>';
  const rows=list.map(c=>'<tr><td>'+esc(c.program)+'</td><td>'+esc(c.chest)+'</td><td>'+esc(c.name)+'</td><td>'+esc(c.team)+'</td>'+(editable?'<td><button class="ghost edit-program" data-edit="'+esc(c.program)+'">Edit</button></td>':'')+'</tr>').join('');
  return '<div class="table-wrap"><table class="table"><thead><tr><th>Programme</th><th>Chest no.</th><th>Name</th><th>Team</th>'+(editable?'<th></th>':'')+'</tr></thead><tbody>'+rows+'</tbody></table></div>';
}
function renderAdminCandidates(){const list=candidates().filter(c=>c.category===state.cat);$('#page').innerHTML=head('ADMINISTRATION','Candidate lists','Review all teams, or create a print-ready list for selected programmes.',`<button id="printBtn" class="secondary no-print">Print selected programmes</button>`)+tabs()+`<section class="card"><div class="toolbar no-print"><div><label>Search</label><input id="candidateSearch" placeholder="Programme, chest no. or name"></div><div><label>Programme filter</label><select id="adminProgram"><option value="">All programmes</option>${programs().filter(p=>p.category===state.cat).map(p=>`<option>${esc(p.name)}</option>`).join('')}</select></div></div><div class="print-only"><h2>WALTAKUN 26 — Candidate List</h2><p>${esc(state.cat)}</p></div><div id="adminCandidateTable">${candidateTable(list)}</div></section>`;attachTabs(renderAdminCandidates);$('#candidateSearch').oninput=filterAdminCandidates;$('#adminProgram').onchange=filterAdminCandidates;$('#printBtn').onclick=printList}
function filterAdminCandidates(){const q=$('#candidateSearch').value.toLowerCase(),p=$('#adminProgram').value;let x=candidates().filter(c=>c.category===state.cat&&(!p||c.program===p)&&(`${c.program} ${c.chest} ${c.name}`.toLowerCase().includes(q)));$('#adminCandidateTable').innerHTML=candidateTable(x)}
function printList(){const options=programs().filter(p=>p.category===state.cat).map(p=>`<label class="student"><input type="checkbox" value="${esc(p.name)}" checked> ${esc(p.name)}</label>`).join('');const modal=document.createElement('div');modal.innerHTML=`<div style="position:fixed;inset:0;background:#0008;display:grid;place-items:center;z-index:10"><div class="card" style="width:min(90vw,440px)"><h3>Choose programmes to print</h3><div class="student-list" style="max-height:300px">${options}</div><div style="display:flex;gap:.6rem;margin-top:1rem"><button class="primary" id="doPrint">Print</button><button class="ghost" id="closePrint">Cancel</button></div></div></div>`;document.body.append(modal);$('#closePrint').onclick=()=>modal.remove();$('#doPrint').onclick=()=>{const wanted=Array.from(modal.querySelectorAll('input:checked')).map(x=>x.value);const old=$('#adminCandidateTable').innerHTML;$('#adminCandidateTable').innerHTML=candidateTable(candidates().filter(c=>c.category===state.cat&&wanted.includes(c.program)));modal.remove();window.print();$('#adminCandidateTable').innerHTML=old}}
function renderResults(){
  if(!isAdmin())return renderPublishedResults();
  const cat=state.resultCat||state.cat||CATS[0];state.resultCat=cat;
  const ps=programs().filter(p=>same(p.category,cat)),current=ps.some(p=>same(p.name,state.program))?state.program:ps[0]?.name;state.program=current;state.cat=cat;
  const entries=candidates().filter(c=>same(c.program,current)&&same(c.category,cat)),existing=results().find(r=>same(r.program,current)&&same(r.category,cat))||{};
  const programmeOptions=ps.map(p=>'<option '+(p.name===current?'selected':'')+'>'+esc(p.name)+'</option>').join('');
  const places=[['first','1st place'],['second','2nd place'],['third','3rd place — optional']].map(x=>{
    const opts=entries.map(c=>'<option value="'+esc(c.chest)+'" '+(existing[x[0]]===c.chest?'selected':'')+'>'+esc(c.name)+' ('+esc(c.chest)+' · '+esc(c.team)+')</option>').join('');
    return '<label class="place"><span>'+x[1][0]+'</span><select id="'+x[0]+'"><option value="">No selection</option>'+opts+'</select></label>';
  }).join('');
  const saved=results(),savedRows=saved.map(r=>'<tr><td>'+esc(r.program)+'</td><td><span class="badge '+r.status.toLowerCase()+'">'+esc(r.status)+'</span></td><td>'+(r.status==='Draft'?'<button class="secondary publish" data-id="'+esc(r.id)+'">Publish</button>':'Published')+'</td></tr>').join('');
  const savedHtml=saved.length?'<div class="table-wrap"><table class="table"><thead><tr><th>Programme</th><th>Status</th><th></th></tr></thead><tbody>'+savedRows+'</tbody></table></div>':'<div class="empty">No results saved.</div>';
  const categoryOptions=CATS.map(c=>'<option '+(same(c,cat)?'selected':'')+'>'+esc(c.toUpperCase())+'</option>').join('');
  $('#page').innerHTML=head('ADMINISTRATION','Results','Choose a category first, then select its programme and add placements.')+'<div class="result-grid"><section class="card"><label>Category</label><select id="resultCategory">'+categoryOptions+'</select><label>Programme</label><select id="resultProgram">'+programmeOptions+'</select><div class="podium" style="margin-top:1.2rem">'+places+'</div><button id="saveResult" class="primary wide">Save draft</button></section><section class="card"><div class="list-head"><h3>Saved results</h3><span class="badge">'+saved.length+'</span></div>'+savedHtml+'</section></div>';
  $('#resultCategory').onchange=e=>{state.resultCat=e.target.value;state.program='';renderResults()};$('#resultProgram').onchange=e=>{state.program=e.target.value;renderResults()};$('#saveResult').onclick=saveResult;document.querySelectorAll('.publish').forEach(b=>b.onclick=()=>publish(b.dataset.id));
}
async function saveResult(){const picked=['first','second','third'].map(k=>$('#'+k).value);if(!picked[0]||!picked[1])return toast('First and second place are required.');if(new Set(picked.filter(Boolean)).size!==picked.filter(Boolean).length)return toast('A candidate cannot have two places.');const p=programs().find(x=>x.name===state.program);const old=results().find(r=>r.program===p.name);try{state.data.results=await api('saveResult',{result:{id:old?.id||'',program:p.name,category:p.category,first:picked[0],second:picked[1],third:picked[2],status:old?.status||'Draft'}});toast('Result saved as draft.');renderResults()}catch(e){toast(e.message)}}
async function publish(id){try{state.data.results=await api('publishResult',{id});toast('Result published.');renderResults()}catch(e){toast(e.message)}}
function renderPublishedResults(){const pub=results().filter(r=>r.status==='Published');const rows=pub.map(r=>'<tr><td><b>'+esc(r.program)+'</b></td><td>'+winner(r.first)+'</td><td>'+winner(r.second)+'</td><td>'+(r.third?winner(r.third):'—')+'</td></tr>').join('');const body=pub.length?'<div class="table-wrap"><table class="table"><thead><tr><th>Programme</th><th>First</th><th>Second</th><th>Third</th></tr></thead><tbody>'+rows+'</tbody></table></div>':'<div class="empty">Results will appear here once the administrator publishes them.</div>';$('#page').innerHTML=head('LIVE RESULTS','Published results','Only confirmed results are shown here.')+'<section class="card">'+body+'</section>'}
function winner(chest){const c=candidates().find(x=>x.chest===chest);return c?`${esc(c.name)} <small>(${esc(c.team)})</small>`:esc(chest)}
function renderWallAdmin(){$('#page').innerHTML=head('DISPLAY WALL','TV slideshow','Open the display link on the TV. It rotates published results and enabled image slides.',`<button id="openWall" class="secondary">Open display wall ↗</button>`)+`<section class="stats"><div class="stat"><b>${results().filter(r=>r.status==='Published').length}</b><span>Published result slides</span></div><div class="stat"><b>${state.data.wall.filter(x=>x.enabled).length}</b><span>Custom image slides</span></div><div class="stat"><b>10s</b><span>Slide timing</span></div></section><section class="card"><h3>Custom wall slides</h3><p class="hint">Add rows to the <b>Wall</b> sheet with a publicly reachable image URL. Slides with Enabled set to TRUE appear after published results.</p><table class="table"><thead><tr><th>Title</th><th>Caption</th><th>Enabled</th></tr></thead><tbody>${state.data.wall.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.caption)}</td><td>${x.enabled?'Yes':'No'}</td></tr>`).join('')||'<tr><td colspan="3">No custom slides yet.</td></tr>'}</tbody></table></section>`;$('#openWall').onclick=()=>window.open(`${location.origin}${location.pathname.replace(/[^/]*$/,'')}wall`,'_blank')}
async function wall(){document.title='WALTAKUN 26 — Display Wall';try{state.data=await api('bootstrap')}catch(e){}const slides=[...results().filter(r=>r.status==='Published').map(r=>({type:'result',r})),...state.data.wall.filter(x=>x.enabled).sort((a,b)=>(a.order||0)-(b.order||0)).map(x=>({type:'image',x}))];if(!slides.length)slides.push({type:'empty'});let i=0;function draw(){const s=slides[i++%slides.length];let body=s.type==='result'?`<div class="eyebrow" style="color:var(--gold)">RESULT ANNOUNCEMENT</div><h1>${esc(s.r.program)}</h1><div class="wall-podium">${[['First',s.r.first],['Second',s.r.second],['Third',s.r.third]].filter(x=>x[1]).map(([p,c])=>`<div class="wall-place"><b>${p} PLACE</b><div>${winner(c)}</div></div>`).join('')}</div>`:s.type==='image'?`<img class="wall-photo" src="${esc(s.x.imageUrl||s.x.image)}" alt="${esc(s.x.title)}"><h1>${esc(s.x.title)}</h1><p class="caption">${esc(s.x.caption)}</p>`:`<h1>WALTAKUN 26</h1><p class="caption">Results will appear here soon.</p>`;$('#app').innerHTML=`<main class="wall"><div class="wall-content">${logo()}${body}</div></main>`}draw();setInterval(draw,10000)}
boot();
